//! `cnbl gen` — emit hexagonal scaffold stubs from a migration plan.

use std::{
    io::{self, BufRead},
    path::{Path, PathBuf},
};

use anyhow::{bail, Context as _};

use crate::{
    ecosystem::{Destination, RouteDecision},
    model::ItemKind,
};

// ============================================================================
// COMMAND
// ============================================================================

pub fn run(
    input: Option<&Path>,
    out_dir: &Path,
    force: bool,
) -> anyhow::Result<()> {
    let decisions = read_plan(input)?;

    // Collect conflicts before writing anything.
    if !force {
        let conflicts: Vec<PathBuf> = decisions
            .iter()
            .flat_map(|d| scaffold_paths(d, out_dir))
            .filter(|p| p.exists())
            .collect();
        if !conflicts.is_empty() {
            let list = conflicts
                .iter()
                .map(|p| format!("  {}", p.display()))
                .collect::<Vec<_>>()
                .join("\n");
            bail!("cnbl gen: conflicts detected (use --force to overwrite):\n{list}");
        }
    }

    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("cannot create out-dir: {}", out_dir.display()))?;

    let mut notes: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();

    for decision in &decisions {
        let dest_name = match &decision.destination {
            Destination::ExistingRepo { name, .. } => name.clone(),
            Destination::NewCrate { suggested_name } => suggested_name.clone(),
            _ => continue,
        };

        let stem = decision
            .item
            .rel_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown")
            .to_string();

        let type_name = to_pascal_case(&stem);
        let source_path = decision.item.rel_path.display().to_string();
        let rationale = &decision.rationale;

        match decision.item.kind {
            ItemKind::DomainLogic => {
                let path = out_dir
                    .join(&dest_name)
                    .join("src/domain")
                    .join(format!("{stem}.rs"));
                write_stub(
                    &path,
                    &format!(
                        "//! Source: {source_path}\n//! Rationale: {rationale}\n//! Generated by cnbl gen v{}\n\n/// Domain type stub.\npub struct {type_name} {{\n    // TODO: port fields from {source_path}\n}}\n",
                        env!("CARGO_PKG_VERSION")
                    ),
                )?;
                notes
                    .entry(dest_name.clone())
                    .or_default()
                    .push(format!("domain/{stem}.rs (from {source_path})"));
            }
            ItemKind::Port => {
                let port_path = out_dir
                    .join(&dest_name)
                    .join("src/ports")
                    .join(format!("{stem}.rs"));
                write_stub(
                    &port_path,
                    &format!(
                        "//! Source: {source_path}\n//! Rationale: {rationale}\n//! Generated by cnbl gen v{}\n\n/// Port trait stub.\npub trait {type_name} {{\n    // TODO: port methods from {source_path}\n}}\n",
                        env!("CARGO_PKG_VERSION")
                    ),
                )?;
                notes
                    .entry(dest_name.clone())
                    .or_default()
                    .push(format!("ports/{stem}.rs (from {source_path})"));

                let adapter_path = out_dir
                    .join(&dest_name)
                    .join("src/adapters")
                    .join(format!("{stem}_stub.rs"));
                write_stub(
                    &adapter_path,
                    &format!(
                        "//! Source: {source_path}\n//! Rationale: {rationale}\n//! Generated by cnbl gen v{}\n\nuse super::super::ports::{stem}::{type_name};\n\npub struct {type_name}Stub;\n\nimpl {type_name} for {type_name}Stub {{\n    // TODO: implement adapter\n    todo!()\n}}\n",
                        env!("CARGO_PKG_VERSION")
                    ),
                )?;
                notes
                    .entry(dest_name.clone())
                    .or_default()
                    .push(format!("adapters/{stem}_stub.rs"));
            }
            ItemKind::Adapter => {
                let path = out_dir
                    .join(&dest_name)
                    .join("src/adapters")
                    .join(format!("{stem}.rs"));
                write_stub(
                    &path,
                    &format!(
                        "//! Source: {source_path}\n//! Rationale: {rationale}\n//! Generated by cnbl gen v{}\n\n/// Adapter stub.\npub struct {type_name} {{\n    // TODO: port adapter from {source_path}\n}}\n",
                        env!("CARGO_PKG_VERSION")
                    ),
                )?;
                notes
                    .entry(dest_name.clone())
                    .or_default()
                    .push(format!("adapters/{stem}.rs (from {source_path})"));
            }
            _ => {} // other kinds not scaffolded
        }
    }

    // Write migration notes per destination.
    for (dest, ported) in &notes {
        let notes_path = out_dir.join(dest).join("migration-notes.md");
        let content = format!(
            "# Migration Notes — {dest}\n\nGenerated by `cnbl gen`.\n\n## Ported\n\n{}\n\n## Next Steps\n\n- Review each stub and port the logic from the source file.\n- Add the module declarations to `src/lib.rs`.\n- Run `cargo build` to check for compile errors.\n",
            ported.iter().map(|s| format!("- {s}")).collect::<Vec<_>>().join("\n")
        );
        write_stub(&notes_path, &content)?;
    }

    eprintln!("cnbl gen: wrote scaffold to {}", out_dir.display());
    Ok(())
}

// ============================================================================
// HELPERS
// ============================================================================

fn read_plan(input: Option<&Path>) -> anyhow::Result<Vec<RouteDecision>> {
    let lines: Box<dyn Iterator<Item = io::Result<String>>> = match input {
        Some(path) => {
            let f = std::fs::File::open(path)
                .with_context(|| format!("cannot open plan file: {}", path.display()))?;
            Box::new(io::BufReader::new(f).lines())
        }
        None => Box::new(io::BufReader::new(io::stdin()).lines()),
    };

    let mut decisions = Vec::new();
    for (i, line) in lines.enumerate() {
        let line = line.with_context(|| format!("read error on line {i}"))?;
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let d: RouteDecision = serde_json::from_str(line)
            .with_context(|| format!("invalid plan JSON on line {i}: {line}"))?;
        decisions.push(d);
    }
    Ok(decisions)
}

fn scaffold_paths(decision: &RouteDecision, out_dir: &Path) -> Vec<PathBuf> {
    let dest_name = match &decision.destination {
        Destination::ExistingRepo { name, .. } => name.clone(),
        Destination::NewCrate { suggested_name } => suggested_name.clone(),
        _ => return vec![],
    };
    let stem = decision
        .item
        .rel_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown")
        .to_string();

    match decision.item.kind {
        ItemKind::DomainLogic => vec![
            out_dir.join(&dest_name).join("src/domain").join(format!("{stem}.rs")),
        ],
        ItemKind::Port => vec![
            out_dir.join(&dest_name).join("src/ports").join(format!("{stem}.rs")),
            out_dir.join(&dest_name).join("src/adapters").join(format!("{stem}_stub.rs")),
        ],
        ItemKind::Adapter => vec![
            out_dir.join(&dest_name).join("src/adapters").join(format!("{stem}.rs")),
        ],
        _ => vec![],
    }
}

fn write_stub(path: &Path, content: &str) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create dir: {}", parent.display()))?;
    }
    std::fs::write(path, content)
        .with_context(|| format!("cannot write stub: {}", path.display()))?;
    eprintln!("  write {}", path.display());
    Ok(())
}

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-'])
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::{
        ecosystem::{Destination, RouteDecision},
        model::{HarvestItem, ItemKind, SourceLang},
    };

    fn make_decision(kind: ItemKind, path: &str, dest: Destination) -> RouteDecision {
        RouteDecision {
            item: HarvestItem {
                rel_path: PathBuf::from(path),
                lang: SourceLang::Rust,
                kind,
                size_bytes: 100,
                notes: None,
            },
            destination: dest,
            rationale: "test".to_string(),
        }
    }

    #[test]
    fn gen_domain_logic_creates_file() {
        let tmp = tempfile::tempdir().unwrap();
        let decisions = vec![make_decision(
            ItemKind::DomainLogic,
            "src/order.rs",
            Destination::ExistingRepo {
                name: "doob".to_string(),
                url: "https://github.com/89jobrien/doob".to_string(),
            },
        )];

        // Write plan to temp file.
        let plan_file = tmp.path().join("plan.jsonl");
        let mut f = std::fs::File::create(&plan_file).unwrap();
        use std::io::Write as _;
        for d in &decisions {
            writeln!(f, "{}", serde_json::to_string(d).unwrap()).unwrap();
        }

        let out = tmp.path().join("output");
        run(Some(&plan_file), &out, false).unwrap();

        let stub = out.join("doob/src/domain/order.rs");
        assert!(stub.exists(), "domain stub should exist");
        let content = std::fs::read_to_string(&stub).unwrap();
        assert!(!content.is_empty());
        assert!(content.contains("Order"));
    }

    #[test]
    fn gen_port_creates_port_and_adapter() {
        let tmp = tempfile::tempdir().unwrap();
        let decisions = vec![make_decision(
            ItemKind::Port,
            "src/storage_port.rs",
            Destination::NewCrate {
                suggested_name: "storers".to_string(),
            },
        )];

        let plan_file = tmp.path().join("plan.jsonl");
        let mut f = std::fs::File::create(&plan_file).unwrap();
        use std::io::Write as _;
        for d in &decisions {
            writeln!(f, "{}", serde_json::to_string(d).unwrap()).unwrap();
        }

        let out = tmp.path().join("output");
        run(Some(&plan_file), &out, false).unwrap();

        assert!(out.join("storers/src/ports/storage_port.rs").exists());
        assert!(out.join("storers/src/adapters/storage_port_stub.rs").exists());
    }

    #[test]
    fn gen_conflict_aborts_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        let decisions = vec![make_decision(
            ItemKind::DomainLogic,
            "src/order.rs",
            Destination::ExistingRepo {
                name: "doob".to_string(),
                url: "https://github.com/89jobrien/doob".to_string(),
            },
        )];

        let plan_file = tmp.path().join("plan.jsonl");
        let mut f = std::fs::File::create(&plan_file).unwrap();
        use std::io::Write as _;
        for d in &decisions {
            writeln!(f, "{}", serde_json::to_string(d).unwrap()).unwrap();
        }

        let out = tmp.path().join("output");
        run(Some(&plan_file), &out, false).unwrap();

        // Run again without force — should error.
        let result = run(Some(&plan_file), &out, false);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("conflicts"));
    }

    #[test]
    fn to_pascal_case_converts_correctly() {
        assert_eq!(to_pascal_case("order_service"), "OrderService");
        assert_eq!(to_pascal_case("storage"), "Storage");
        assert_eq!(to_pascal_case("my_domain_type"), "MyDomainType");
    }
}
